Rename to cms chronic conditions
tuva-health/cms_chronic_conditions pull request #28
Opened 2022-12-19 19:34 UTC by thutuva

## Describe your changes
Please include a summary of any changes.
 - renamed all references from chronic_conditions to cms_chronic_conditions
 
## How has this been tested?
Please describe the tests you ran to verify your changes.  Provide instructions or code to reproduce output.
- executed dbt build in both snowflake and redshift
- ran through the testing steps in the [package development guide](https://www.notion.so/tuvahealth/WIP-Package-Development-Guide-21198e3e273a4549bd014073477a7f94) to ensure that variables were updated and working properly

## Reviewer focus
Please summarize the specific items you’d like the reviewer(s) to look into.
- Please ensure that all package references to chronic_conditions have been rename to cms_chronic_conditions

## Checklist before requesting a review
- [x]  I have recorded a Loom performing a self-review of my code
- [x]  My code follows style guidelines
- [x]  I have commented my code as necessary
- [x]  I have testing by code by running `dbt build` in the following warehouse(s):
    - [x]  Snowflake
    - [x]  Redshift
- [ ]  I have implemented generic dbt tests to validate primary keys/uniqueness in my model
- [x]  I have updated dbt docs by running `dbt docs generate` and copying the appropriate files to the `docs/` path
- [x]  I have added at least one Github label to this PR

## (Optional) Gif of how this PR makes you feel
<img src="https://media3.giphy.com/media/r83vi3NbJg90dAyb6b/giphy.gif"/>

## Loom link
https://www.loom.com/share/2afabb1f372d4ec4a26dd727820d76a8

## For reviewers:
[Best practices for reviewing pull requests.](https://www.notion.so/Pull-Request-Review-Best-Practices-b486354d76c04982889f2178fe777c1c)

2022-12-19 19:59 UTC, aneiderhiser requested changes
The only changes I think we need to make are to update the README (i.e. reference CMS Chronic Conditions).

2022-12-19 20:15 UTC, thutuva commented
@aneiderhiser I've updated the ReadMe, thanks for catching that!  Let me know if you're happy with these changes.

2022-12-19 20:19 UTC, aneiderhiser approved these changes
Looks good!

2022-12-20 20:55 UTC, sarah-tuva reviewed
@thutuva This seemed like a pain to do. Sorry! I think I found a couple of things.

2022-12-20 20:55 UTC, sarah-tuva commented on docs/docs_generate/dbt_project.yml
>    - macro_namespace: dbt
@thutuva Do you know if the package name needs to be updated here as well? I'm not super familiar with what the docs_generate files do.

2022-12-20 20:55 UTC, sarah-tuva commented on docs/docs_generate/models/condition.sql
> +from tuva_claims_demo_sample.core.condition
@thutuva Is this supposed to be pointing to the tuva_claims_demo_sample database? This is listed in all of the models under the docs_generate path.

2022-12-20 20:55 UTC, sarah-tuva commented on integration_tests/dbt_project.yml
> +# terminology_enabled: false
I love how you cleaned up the vars in this file. 👏

2022-12-20 20:55 UTC, sarah-tuva commented on models/_models.yml
>        alias: chronic_conditions_pivoted
@thutuva Do the aliases need to be updated as well or are we not concerned about overlap with the Tuva version?

2022-12-20 22:21 UTC, thutuva commented on docs/docs_generate/dbt_project.yml
>    - macro_namespace: dbt
It does need to be updated here but this is only an example config.  The real variable that drives this behavior is in the main package's [dbt_project.yml](https://github.com/tuva-health/cms_chronic_conditions/blob/rename-to-cms_chronic_conditions/dbt_project.yml)

2022-12-20 22:22 UTC, thutuva commented on docs/docs_generate/models/condition.sql
> +from tuva_claims_demo_sample.core.condition
Yes, this should point to the demo data.  We are mainly this query to create the metadata for the docs.

2022-12-20 22:28 UTC, thutuva commented on models/_models.yml
>        alias: chronic_conditions_pivoted
I did not update the alias because the schema name should clear up any confusion there may be if table names have the same name or are similar.  

When we had previously discussed using an alias (from what I recall during that team meeting with Taylor) we decided to use a 'clean name' without the package name because the package name is the schema name.  So we wanted to cut out the redundant nature of something like `tuva.cms_chronic_condition.cms_chronic_condition__hronic_conditions_pivoted`.

2022-12-21 16:33 UTC, merged